// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

import (
	"github.com/harshpreet93/next-gqlgen-ent/backend/ent"
)

type PetInput struct {
	ID      *int   `json:"id"`
	OwnerID int    `json:"ownerID"`
	Name    string `json:"name"`
}

// The connection between users and pets
type UserPetConnection struct {
	TotalCount int            `json:"totalCount"`
	Edges      []*UserPetEdge `json:"edges"`
	PageInfo   *ent.PageInfo  `json:"pageInfo"`
}

// The edge of the user pet connection
type UserPetEdge struct {
	Cursor int      `json:"cursor"`
	Node   *ent.Pet `json:"node"`
}
