// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (pe *Pet) Owner(ctx context.Context) ([]*User, error) {
	result, err := pe.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = pe.QueryOwner().All(ctx)
	}
	return result, err
}

func (u *User) Pet(ctx context.Context) ([]*Pet, error) {
	result, err := u.Edges.PetOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryPet().All(ctx)
	}
	return result, err
}
