// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/harshpreet93/next-gqlgen-ent/backend/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
